theme: jekyll-theme-minimal
title: NopeGuides
description: A place for NopeNopeGuy's guides
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: RBE for Android Using Buildbuddy
    url: rbe
